### ISSUE TITLE
Issue with ThrowableFireballs

### ISSUE THREAD

**Issue by AdminHcat** [FlailoftheLord/ThrowableFireballs#5]
**Describe the bug**
1、Creative mode  will also consume the number of items
2、Spectator Mode  also can  throw fireballs
3、some pvp plugin will add a temporary flag to the item to facilitate PVP to end the recovery of items ,but bucause the flag, the fireball can't be used

**Expected behavior**

**Steps to reproduce this problem**

**Screenshots**

**Additional context**

**Comment by AdminHcat** [comment]
A flag can be added for judgment, so that even if the item information of the fireball is modified, it can still be used, and this problem can be solved

**Comment by FlailoftheLord** [comment]
Don't have time for any coding rn, will get to it when i do.
No timeframe.
Feel free to submit a pr.

**Comment by FlailoftheLord** [comment]
https://github.com/FlailoftheLord/ThrowableFireballs/commit/a82e5e51ed10b514d221f1733a61759ad02626fa
